# Generated by Django 5.1.7 on 2025-03-10 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnname', models.CharField(max_length=1024)),
                ('description', models.TextField(default='')),
                ('severity', models.CharField(default='info', max_length=50)),
                ('reference', models.CharField(default='', max_length=2048)),
                ('scan_date', models.DateTimeField(null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('last_reported', models.DateTimeField(blank=True, null=True)),
                ('reported', models.BooleanField(default=False)),
                ('source', models.CharField(default='nuclei', max_length=200)),
                ('cvssscore', models.CharField(default='', max_length=1024)),
                ('cveid', models.CharField(default='', max_length=1024)),
                ('cvssmetrics', models.CharField(default='', max_length=1024)),
                ('solution', models.TextField(default='')),
                ('vulnerableAt', models.CharField(default='', max_length=2048)),
                ('vulnerabilityDetails', models.CharField(blank=True, default='', max_length=4096, null=True)),
                ('raw', models.JSONField(null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.activedomain')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateTimeField(null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(default='info', max_length=50)),
                ('port', models.IntegerField()),
                ('banner', models.CharField(default='', max_length=2048)),
                ('status', models.CharField(default='open', max_length=50)),
                ('product', models.CharField(default='', max_length=2048)),
                ('cpe', models.CharField(default='', max_length=2048)),
                ('raw', models.JSONField(null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.activedomain')),
            ],
        ),
    ]
