# Generated by Django 5.1.7 on 2025-03-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='domain_name',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
