# Generated by Django 5.1.7 on 2025-03-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0002_port_domain_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finding',
            old_name='cveid',
            new_name='cve',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='vulnname',
        ),
        migrations.AddField(
            model_name='finding',
            name='domain_name',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='finding',
            name='name',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='finding',
            name='type',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='finding',
            name='url',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='finding',
            name='severity',
            field=models.CharField(default='', max_length=50),
        ),
    ]
