# Generated by Django 5.1.7 on 2025-03-12 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=1024, unique=True)),
                ('description', models.TextField(default='')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=1024)),
                ('description', models.TextField(default='')),
                ('enabled', models.BooleanField(default=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('ktype', models.CharField(default='registrant_org', max_length=1024)),
                ('related_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveIP',
            fields=[
                ('value', models.CharField(default='', max_length=2048)),
                ('uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('source', models.CharField(default='', max_length=200)),
                ('creation_time', models.DateTimeField()),
                ('lastscan_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(default='')),
                ('link', models.CharField(max_length=1024)),
                ('monitor', models.BooleanField(default=True)),
                ('related_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.keyword')),
                ('related_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveDomain',
            fields=[
                ('finding_subtype', models.CharField(default='domain', max_length=100)),
                ('value', models.CharField(default='', max_length=2048)),
                ('uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('source', models.CharField(default='', max_length=200)),
                ('creation_time', models.DateTimeField()),
                ('lastscan_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(default='')),
                ('link', models.CharField(blank=True, default='', max_length=1024)),
                ('monitor', models.BooleanField(default=True)),
                ('related_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.keyword')),
                ('related_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveCertificate',
            fields=[
                ('value', models.CharField(default='', max_length=2048)),
                ('uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('source', models.CharField(default='', max_length=200)),
                ('creation_time', models.DateTimeField()),
                ('description', models.TextField(default='')),
                ('link', models.CharField(max_length=1024)),
                ('cert_valid', models.BooleanField(default=True)),
                ('cert_wildcard', models.BooleanField(default=False)),
                ('monitor', models.BooleanField(default=True)),
                ('related_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.keyword')),
                ('related_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(default='', max_length=2048)),
                ('related_ips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.activeip')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('related_domains', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.activedomain')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('finding_type', models.CharField(default='domain', max_length=100)),
                ('finding_subtype', models.CharField(default='subdomain', max_length=100)),
                ('value', models.CharField(default='', max_length=2048)),
                ('uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('source', models.CharField(default='', max_length=200)),
                ('creation_time', models.DateTimeField()),
                ('description', models.TextField(default='')),
                ('active', models.BooleanField(default=True)),
                ('link', models.CharField(blank=True, default='', max_length=1024)),
                ('cert_valid', models.BooleanField(default=True)),
                ('cert_wildcard', models.BooleanField(default=False)),
                ('ignore', models.BooleanField(default=False)),
                ('is_monitored', models.BooleanField(default=False)),
                ('raw', models.JSONField(default=None, null=True)),
                ('related_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.keyword')),
                ('related_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
