# Generated by Django 5.1.7 on 2025-03-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='active',
            field=models.CharField(default='Ignored', max_length=100),
        ),
    ]
